Libros/Libros/Models/Libro.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Libro
    {
        public Libro()
        {
            this.AutorLibro = new HashSet<AutorLibro>();
        }
    
        public int IdLibro { get; set; }
        public string Titulo { get; set; }

        public System.DateTime FechaEdicion { get; set; }

        public int Autores { get; set; }
    
        public virtual ICollection<AutorLibro> AutorLibro { get; set; }
    }
}

Libros/Libros/Models/Libros.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Libros/Libros/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Libros.Models;

namespace Libros.Controllers
{
    public class LibroController : Controller
    {
        private LibrosEntities db = new LibrosEntities();

        // GET: /Libro/
        public ActionResult Index()
        {
            List<Libro> libros = new List<Libro>();
            libros = db.Libro.ToList();

            foreach(Libro libro in libros)
            {
                libro.Autores = db.AutorLibro.Where(al => al.IdLibro == libro.IdLibro).Count();
            }

            return View(libros);
        }

        // GET: /Libro/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            return View(libro);
        }

        // GET: /Libro/Create
        public ActionResult Create()
        {
            List<Autor> autores = new List<Autor>();
            autores = db.Autor.ToList();
            ViewBag.AllAutores = autores;
            return View();
        }

        // POST: /Libro/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Titulo,FechaEdicion")] Libro libro, int[] idsAutores)
        {
            if (ModelState.IsValid && idsAutores != null)
            {
                db.Libro.Add(libro);
                db.SaveChanges();
                int idLibro = libro.IdLibro;

                foreach (var autorId in idsAutores)
                {
                    Autor autor = new Autor();
                    autor = db.Autor.FirstOrDefault(a => a.IdAutor == autorId);
                    AutorLibro autorLibro = new AutorLibro();
                    autorLibro.Autor = autor;
                    autorLibro.Libro = libro;
                    db.AutorLibro.Add(autorLibro);
                    db.SaveChanges();
                }

                
                return RedirectToAction("Index");
            }

            else
            {
                List<Autor> autores = new List<Autor>();
                autores = db.Autor.ToList();
                ViewBag.AllAutores = autores;
                return View(libro);
            }
        }

        // GET: /Libro/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }

            List<Autor> autores = new List<Autor>();
            autores = db.Autor.ToList();
            foreach (Autor autor in autores)
            {
                bool selected = db.AutorLibro.Any(a => a.IdAutor == autor.IdAutor && a.IdLibro == id);
                autor.Selected = selected;
            }
            ViewBag.AllAutores = autores;


            return View(libro);
        }

        // POST: /Libro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdLibro,Titulo,FechaEdicion")] Libro libro, int[] idsAutores)
        {
            if (ModelState.IsValid && idsAutores != null)
            {
                db.Entry(libro).State = EntityState.Modified;
                db.SaveChanges();

                List<AutorLibro> actualList = new List<AutorLibro>();
                actualList = db.AutorLibro.Where(a => a.IdLibro == libro.IdLibro).Select(al => al).ToList();

                foreach (AutorLibro actualLibro in actualList)
                {
                    db.AutorLibro.Remove(actualLibro);
                }

                foreach (var autorId in idsAutores)
                {
                    Autor autor = new Autor();
                    autor = db.Autor.FirstOrDefault(a => a.IdAutor == autorId);
                    AutorLibro autorLibro = new AutorLibro();
                    autorLibro.Autor = autor;
                    autorLibro.Libro = libro;
                    db.AutorLibro.Add(autorLibro);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            else
            {
                List<Autor> autores = new List<Autor>();
                autores = db.Autor.ToList();
                ViewBag.AllAutores = autores;
                return View(libro);
            }
        }

        // GET: /Libro/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            return View(libro);
        }

        // POST: /Libro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Libro libro = db.Libro.Find(id);
            db.Libro.Remove(libro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
        public ActionResult Search(string titulo, DateTime? edicion, string autor)
        {
            int numAutores = autor!=""? Convert.ToInt32(autor) : 0;
            List<Libro> libros = new List<Libro>();


            libros = db.Libro.Where(l => l.Titulo.Contains(titulo) || l.FechaEdicion == edicion || l.AutorLibro.Count() == numAutores).ToList();

            foreach (Libro libro in libros)
            {
                libro.Autores = db.AutorLibro.Where(al => al.IdLibro == libro.IdLibro).Count();
            }

            return View("Index",libros);
        }
    }
}

Libros/Libros/Views/Libro/Create.cshtml
@model Libros.Models.Libro

@{
    ViewBag.Title = "Create";
}

<h2>Agregar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="col-md-offset-1 col-md-5">
            <div class="form-group">
                <label class="control-label col-md-2">Título</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo)
                    @Html.ValidationMessageFor(model => model.Titulo)
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Edición</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaEdicion)
                    @Html.ValidationMessageFor(model => model.FechaEdicion)
                </div>
            </div>
           </div>
        <div class="col-md-offset-1 col-md-5">
            <table class="table">
                <tr>
                    <th>
                       Nombre
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in ViewBag.AllAutores)
                {
                    <tr>
                        <td>
                            @item.Nombre
                        </td>
                       <td>
                           <input type="checkbox" name="idsAutores" value="@item.IdAutor" />
                       </td>
                    </tr>
                }

            </table>
</div>
            <div class="form-group">
                <div class="col-md-offset-1 col-md-5">
                    <input type="submit" value="Guardar" class="btn btn-default" />
                </div>
                <div class="col-md-offset-1 col-md-5">
                    @Html.ActionLink("Cancel", "Index", null, new { @class="btn btn-default" })
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Listado de Libros", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Libros/Libros/Views/Libro/Delete.cshtml
@model Libros.Models.Libro

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEdicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEdicion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Libros/Libros/Views/Libro/Details.cshtml
@model Libros.Models.Libro

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Libro</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEdicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEdicion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdLibro }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Libros/Libros/Views/Libro/Edit.cshtml
@model Libros.Models.Libro

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.IdLibro)
        <div class="col-md-offset-1 col-md-5">
            <div class="form-group">
                <label class="control-label col-md-2">Título</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo)
                    @Html.ValidationMessageFor(model => model.Titulo)
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Edición</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaEdicion)
                    @Html.ValidationMessageFor(model => model.FechaEdicion)
                </div>
            </div>
       </div>
        <div class="col-md-offset-1 col-md-5">
            <table class="table">
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th></th>
                </tr>
               
                @foreach (var item in ViewBag.AllAutores)
                {
                    <tr>
                        <td>
                            @item.Nombre
                        </td>
                        <td>
                            <input type="checkbox" name="idsAutores" value="@item.IdAutor" checked="@item.Selected" />
                        </td>
                    </tr>
                }

            </table>
        </div>
            <div class="form-group">
                <div class="col-md-offset-1 col-md-5">
                    <input type="submit" value="Guardar" class="btn btn-default" />
                </div>
                <div class="col-md-offset-1 col-md-5">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Listado de Libros", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Libros/Libros/Views/Libro/Index.cshtml
@model IEnumerable<Libros.Models.Libro>

@{
    ViewBag.Title = "Index";
}

<h2>Listar Libros</h2>

<p>
    @Html.ActionLink("Nuevo Libro", "Create")
</p>

@using (Html.BeginForm("Search", "Libro"))
{
<div class="col-md-offset-1 col-md-5">
    <div class="form-group">
        <label class="control-label col-md-2">Título</label>
        <div class="col-md-10">
            <input type="text" name="titulo" id="titulo" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Edición</label>
        <div class="col-md-10">
            <input type="date" name="edicion" />
        </div>
    </div>
</div>
<div class="col-md-offset-1 col-md-5">
    <div class="form-group">
        <label class="control-label col-md-2">Autor</label>
        <div class="col-md-10">
            <input type="text" name="autor" />
        </div>
        </div>
    <div class="form-group">
        <input type="submit" title="Delete" value="Buscar" />
    </div>
    </div>
}
    <table class="table">
        <tr>
            <th>
                Título
            </th>
            <th>
                Edición
            </th>
            <th>
                Autores
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaEdicion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Autores)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdLibro }) 
                </td>
            </tr>
        }

    </table>